### ISSUE TITLE
version 0.6 fails on pip install

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#25]
When trying to install sentinelsat through pip it seems to be missing the requirements.txt.

```bash
vm:~$ pip install sentinelsat --no-cache-dir
Collecting sentinelsat
  Downloading sentinelsat-0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-a84kSh/sentinelsat/setup.py", line 30, in <module>
        install_requires=open('requirements.txt').read().splitlines(),
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a84kSh/sentinelsat
```

Installing from github works fine:

```bash
vm:~$ git clone https://github.com/ibamacsr/sentinelsat.git
vm:~$ cd sentinelsat/
vm:~$ python setup.py install
...
Finished processing dependencies for sentinelsat==0.6
```

This was reproduced multiple times on Win_x64 with Python 2.7 & 3.4 as well as Ubuntu 14.04 with the system Python 2.7.

**Comment by willemarcel** [comment]
The requirements.txt wasn't included in the source package on pypi. I added a MANIFEST.in which fixed it. Thank you for the advice.

https://github.com/ibamacsr/sentinelsat/commit/751cb06a4d1a3f06cac4f1e850e2469be6fc325f
