### ISSUE TITLE
HTTP Status 500 - connect timed out

### ISSUE THREAD

**Issue by lucadelu** [ibamacsr/sentinelsat#67]
Hi,

I'm new user of sentinelsat and I often get "HTTP Status 500 - connect timed out" response when I try to search. Is the problem on my request? (maybe the geojson is too big I'm trying to get scenes for Italy) or is the problem server side?

Thanks 
Luca

```
sentinel search --sentinel2 -s 20160701 -e 20160801 -c 5 USER PASSWD italia_bbox.json 

Traceback (most recent call last):
  File "/usr/local/bin/sentinel", line 11, in <module>
    load_entry_point('sentinelsat==0.7.1', 'console_scripts', 'sentinel')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sentinelsat-0.7.1-py2.7.egg/sentinelsat/scripts/cli.py", line 86, in search
    api.query(get_coordinates(geojson), start, end, **search_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sentinelsat-0.7.1-py2.7.egg/sentinelsat/sentinel.py", line 143, in query
    self.load_query(query)
  File "/usr/local/lib/python2.7/dist-packages/sentinelsat-0.7.1-py2.7.egg/sentinelsat/sentinel.py", line 158, in load_query
    _check_scihub_response(content)
  File "/usr/local/lib/python2.7/dist-packages/sentinelsat-0.7.1-py2.7.egg/sentinelsat/sentinel.py", line 98, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: (HTTP status: 500, code: None) 
# HTTP Status 500 - connect timed out

* * *

**type** Exception report

**message** _connect timed out_

**description** _The server encountered an internal error that prevented it from fulfilling this request._

**exception**
    
    
    java.net.SocketTimeoutException: connect timed out
    	java.net.PlainSocketImpl.socketConnect(Native Method)
    	java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    	java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    	java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    	java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    	java.net.Socket.connect(Socket.java:579)
    	sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    	sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    	sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    	sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    	sun.net.www.http.HttpClient.New(HttpClient.java:308)
    	sun.net.www.http.HttpClient.New(HttpClient.java:326)
    	sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
    	sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
    	sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
    	sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
    	fr.gael.dhus.server.http.webapp.search.controller.SearchController.search(SearchController.java:164)
    	fr.gael.dhus.server.http.webapp.search.controller.SearchController$$FastClassBySpringCGLIB$$e2477ad5.invoke(<generated>)
    	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
    	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    	org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
    	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
    	fr.gael.dhus.server.http.webapp.search.controller.SearchController$$EnhancerBySpringCGLIB$$b1be1407.search(<generated>)
    	sun.reflect.GeneratedMethodAccessor371.invoke(Unknown Source)
    	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	java.lang.reflect.Method.invoke(Method.java:606)
    	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
    	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
    	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
    	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
    	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
    	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
    	javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
    	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
    	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
    	fr.gael.dhus.spring.CacheControlFilter.doFilter(CacheControlFilter.java:47)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	fr.gael.dhus.spring.security.filter.PreAuthFilter.doFilter(PreAuthFilter.java:79)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
    	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
    	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
    	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
    	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
    

**note** _The full stack trace of the root cause is available in the Apache Tomcat/7.0.47 logs._

* * *

### Apache Tomcat/7.0.47

```

**Comment by Fernerkundung** [comment]
With your query and a [polygon of italy](https://gist.github.com/Fernerkundung/45802b0bbd22337165e44d61181b8f58) I get a result of 37 scenes. Tested with `sentinelsat 0.7.1` on Win x64 and Ubuntu 16.04:

```
Product 08a8e4a6-e5fb-42c0-a2c8-9cf5f8aff9e2 - Date: 2016-07-25T10:00:32Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 6.88 GB
Product 32efcd79-d186-4fa9-9228-d4b65c84eba6 - Date: 2016-07-28T10:16:03Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 5.80 GB
.
.
.
Product cc3f2902-1e48-48bc-a7ef-1b3060a09286 - Date: 2016-07-02T09:52:19Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 2.11 GB
---
37 scenes found with a total size of 188.96 GB
```

Is the error persistent on your end or sporadic? As you might know scihub is known for its server outages due to high demand for the data. A HTTP 5xx is a server side issue and I'd guess it was one of their outages due to high load.

Search polygons are limited to 200 vertices (as per scihubs documentation), but I successfully used larger polygons.

If the error is persistent on your end could you give us more details on your environment please? Might be some weird pycurl issue - which seems to be our most troublesome dependency (together with SSL).

**Comment by valgur** [comment]
I have been receiving error 500s today, as well, sporadically. This is definitely a SciHub issue.

Maybe we should add a sort of a FAQ in `CONTRIBUTING.md` that describes what issues are likely to be caused by SciHub. Check out https://github.com/pycurl/pycurl/issues/new for an example.

**Comment by lucadelu** [comment]
Today I was able to query scihub (before the maintenance mode), sorry for the noise, but today ago I was not able to perform queries for the entire day
